name: "OWASP Dependency Check"
on:
  push:
    branches:
      - owsap-call 
  pull_request:
    branches:
      - owsap-call 
jobs:
  dependency-check:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/owasp-dependency-check.yml@main
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
